export type Product = { id:string; slug:string; name:string; category:string; price:number; old_price?:number; weight:string; stock:number; tags:string[]; image:string; description:string; ingredients:string; nutrition:{kcal:number;protein:number;fat:number;carbs:number}; featured:boolean; created_at?:string };
export const categories = [
 {id:'superfoods',name:'Суперфуди та насіння',icon:'sprout',color:'#ecf0df'},
 {id:'nuts',name:'Горіхи та сухофрукти',icon:'nut',color:'#f4e9da'},
 {id:'sweets',name:'Корисні солодощі',icon:'cookie',color:'#f4e4dc'},
 {id:'tea',name:'Натуральні чаї та трави',icon:'coffee',color:'#e5ecdd'},
 {id:'oils',name:'Олії та горіхові пасти',icon:'jar',color:'#f3edd8'},
 {id:'care',name:'Косметика та догляд',icon:'flower',color:'#eee7ed'}
];
export const products:Product[]=[
 {id:'chia',slug:'nasinnia-chia',name:'Насіння чіа',category:'superfoods',price:149,old_price:179,weight:'200 г',stock:42,tags:['Веган','Без глютену','RAW'],image:'/images/chia.jpg',description:'Маленьке насіння для великих ідей. Додавайте до ранкової каші, смузі або залишайте на ніч із рослинним молоком для ніжного чіа-пудингу.',ingredients:'Насіння чіа 100%. Може містити сліди горіхів.',nutrition:{kcal:486,protein:16.5,fat:30.7,carbs:42.1},featured:true},
 {id:'almond',slug:'myhdal-syryi',name:'Мигдаль сирий',category:'nuts',price:219,weight:'250 г',stock:35,tags:['Веган','Без цукру','RAW'],image:'/images/almond.jpg',description:'Добірний хрусткий мигдаль із ніжним смаком. Для корисного перекусу, домашньої граноли та улюбленої випічки.',ingredients:'Мигдаль 100%. Алерген: горіхи.',nutrition:{kcal:579,protein:21.2,fat:49.9,carbs:21.6},featured:true},
 {id:'peanut',slug:'arakhisova-pasta',name:'Арахісова паста кранч',category:'oils',price:189,old_price:215,weight:'300 г',stock:18,tags:['Веган','Без цукру','Без глютену'],image:'/images/peanut.jpg',description:'Густа арахісова паста з хрусткими шматочками. Лише обсмажений арахіс — жодного доданого цукру чи пальмової олії.',ingredients:'Арахіс обсмажений 100%. Алерген: арахіс.',nutrition:{kcal:588,protein:25,fat:50,carbs:20},featured:true},
 {id:'tea',slug:'chai-miata-melisa',name:'Трав’яний чай «Тиха мить»',category:'tea',price:129,weight:'50 г',stock:26,tags:['Веган','Без цукру'],image:'/images/tea.jpg',description:'Ароматний трав’яний збір для затишних вечорів. М’ята, меліса та ромашка в одній чашці спокою.',ingredients:'М’ята, меліса, квіти ромашки.',nutrition:{kcal:2,protein:0,fat:0,carbs:0.4},featured:true},
 {id:'apricot',slug:'kuraha-naturalna',name:'Курага натуральна',category:'nuts',price:169,weight:'250 г',stock:30,tags:['Веган','Без цукру'],image:'/images/apricot.jpg',description:'М’які сушені абрикоси без доданого цукру. Природна солодкість до чаю та сніданків.',ingredients:'Абрикос сушений 100%.',nutrition:{kcal:241,protein:3.4,fat:0.5,carbs:63},featured:false},
 {id:'bar',slug:'granola-bar',name:'Гранола-бар із горіхами',category:'sweets',price:59,weight:'45 г',stock:60,tags:['Веган','Без цукру'],image:'/images/bar.jpg',description:'Солодкий перекус із фініків, горіхів та какао. Зручно взяти на прогулянку або до кави.',ingredients:'Вівсяні пластівці, фініки, мигдаль, насіння, какао. Алергени: глютен, горіхи.',nutrition:{kcal:380,protein:7,fat:14,carbs:55},featured:false},
 {id:'oil',slug:'oliia-olyvkova',name:'Олія оливкова extra virgin',category:'oils',price:279,weight:'250 мл',stock:15,tags:['Веган','Без глютену'],image:'/images/oil.jpg',description:'Насичена олія холодного віджиму для салатів, крем-супів та овочевих страв.',ingredients:'Олія оливкова першого холодного віджиму 100%.',nutrition:{kcal:884,protein:0,fat:100,carbs:0},featured:false},
 {id:'soap',slug:'mylo-miata',name:'Натуральне мило «М’ята»',category:'care',price:119,weight:'100 г',stock:22,tags:['Веган'],image:'/images/soap.jpg',description:'М’яке мило на основі рослинних олій із свіжим ароматом м’яти. Для щоденного догляду за руками.',ingredients:'Омилені оливкова та кокосова олії, вода, гліцерин, ефірна олія м’яти.',nutrition:{kcal:0,protein:0,fat:0,carbs:0},featured:false}
];
export const money=(value:number)=>new Intl.NumberFormat('uk-UA',{maximumFractionDigits:0}).format(value)+' ₴';
